apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactionsdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: githubactionsdemo
  template:
    metadata:
      labels:
        app: githubactionsdemo
    spec:
      containers:
        - name: githubactionsdemo
          image: 850995558598.dkr.ecr.us-east-2.amazonaws.com/springboot-eks:1.1
          ports:
            - containerPort: 8282

---
apiVersion: v1
kind: Service
metadata:
  name: githubactionsdemo-service
spec:
  selector:
    app: githubactionsdemo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8282
  type: LoadBalancer